### ISSUE TITLE
Sidebar overlaps navbar

### ISSUE THREAD

**Issue by biwasbhandari** [aibtcdev/aibtcdev-frontend#101]
![image](https://github.com/user-attachments/assets/b5375413-f22c-4179-af53-926a669263e7)

**Comment by whoabuddy** [comment]
Fixed! Should support mobile and made it a little wider.

![Screenshot from 2024-11-10 00-12-06](https://github.com/user-attachments/assets/ad625ed0-58f3-4567-a600-03c3bf4b5083)
![Screenshot from 2024-11-10 00-12-19](https://github.com/user-attachments/assets/d19ba34c-dc0d-4fd3-97f1-a7b7b1aee3e2)
