### ISSUE TITLE
layout: header updates

### ISSUE THREAD

**Issue by whoabuddy** [aibtcdev/aibtcdev-frontend#12]
- [x] remove home/about buttons in center
- [x] replace with AIBTC.dev text (extra wide font) or logo image in center, link to dashboard
- [ ] add STX address left of sign-out button, can be full or truncated 5:5 (SP123...21XYZ)
- [x] remove divider between header/body, use padding as natural transition

**Comment by whoabuddy** [comment]
All but one completed in #12

**Comment by whoabuddy** [comment]
Copying over comment [from the PR](https://github.com/aibtcdev/aibtcdev-frontend/pull/22#issuecomment-2436129792)

> @biwasbhandari curious the best way we can store the stacks address at login for reuse in another component? I'd default to jotai but curious if there's an easier way given our infra.

**Comment by biwasbhandari** [comment]
I prefer redux but I've used it only once.

**Comment by whoabuddy** [comment]
Fixed in #27
