### ISSUE TITLE
Improve performance warning.

### ISSUE THREAD

**Issue by biwasbhandari** [aibtcdev/aibtcdev-frontend#131]
![image](https://github.com/user-attachments/assets/cb5fab02-a6a7-4afe-bab1-f509380bc561)
Not sure why I am getting this warning but its due to performance issue.

**Comment by whoabuddy** [comment]
Is this resolved now or still present? I've seen it before but what steps to reproduce?

**Comment by r0zar** [comment]
I've seen this with big tool/chat responses, like getting all price data. I'd need to reproduce to be sure tho.
