### ISSUE TITLE
Unable to select agent from task

### ISSUE THREAD

**Issue by whoabuddy** [aibtcdev/aibtcdev-frontend#15]
I added an agent with the latest, but the agent didn't populate when I went to add a task:

![image](https://github.com/user-attachments/assets/fd8e8bcf-6602-4b08-8fdd-ade2a5f51ef3)

Shows up after refresh:

![image](https://github.com/user-attachments/assets/929bf79a-5e4a-4ae9-8871-54beb7a6362b)

**Comment by biwasbhandari** [comment]
fixed with https://github.com/aibtcdev/aibtcdev-frontend/pull/27

**Comment by biwasbhandari** [comment]
It's back again
