### ISSUE TITLE
Task assignment flow

### ISSUE THREAD

**Issue by whoabuddy** [aibtcdev/aibtcdev-frontend#16]
Should tasks be allowed to exist without agents?

If we allow it on the creation we should allow it on the edit too, e.g. unselecting the agent here:

![image](https://github.com/user-attachments/assets/61661671-d1e2-4272-aae6-ca6454e1c149)

But it might make more sense to restrict task creation until agents > 0, then require a task is assigned to an agent?

**Comment by whoabuddy** [comment]
Feeling like easiest path forward is require an assignment after #15 is resolved.

**Comment by biwasbhandari** [comment]
looks like fixed. once we add an agent we can see it when adding a task too.
