### ISSUE TITLE
Create default crew

### ISSUE THREAD

**Issue by whoabuddy** [aibtcdev/aibtcdev-frontend#31]
We should start everyone off with a simple crew so they can then choose to modify or create their own in the settings.

- researcher agent per category of tools (ALEX, Bitflow, LunarCrush)
- trade executor that takes researcher results and decides to do something

Bonus points if we can provide balance info as part of the prompt (query then pass).

**Comment by whoabuddy** [comment]
Related: #13 and #26

**Comment by biwasbhandari** [comment]
solved with https://github.com/aibtcdev/aibtcdev-frontend/pull/34
