### ISSUE TITLE
Allow Users to Add Custom Crew Without Cloning Starter Crew

### ISSUE THREAD

**Issue by biwasbhandari** [aibtcdev/aibtcdev-frontend#69]
Without cloning our crew we are not able to see an option to add user's own crew. 
Is that a feature or do we have to fix it and let users add their crew without cloning our starter crew?
![image](https://github.com/user-attachments/assets/f1a805f7-e931-4161-8066-f297aaddeba3)
![image](https://github.com/user-attachments/assets/02b57e35-fdc4-4392-af74-8ae607c46a81)

**Comment by whoabuddy** [comment]
We should allow them to create a crew or clone ours, it's fine for them to jump right in.

We should probably make sure someone cannot execute a crew unless they have at least 1 agent and 1 task as well, with clear errors so the user knows what action(s) to take.

**Comment by whoabuddy** [comment]
Fixed in #77 but also caused #82
