### ISSUE TITLE
Double check admin page filters

### ISSUE THREAD

**Issue by whoabuddy** [aibtcdev/aibtcdev-frontend#88]
I noticed my normal list isn't so normal!

![Screenshot from 2024-11-07 09-54-22](https://github.com/user-attachments/assets/7188aa87-20ba-4934-98f4-0e7cbf56bb95)

![Screenshot from 2024-11-07 09-54-31](https://github.com/user-attachments/assets/ea6837d2-28e2-4863-91da-428c9cc8c265)

**Comment by biwasbhandari** [comment]
It seems that users with a null role were also being displayed as normal users when their role was null in the database, which caused the filtering issue. fixed here #98
