### ISSUE TITLE
Persist chats on refresh

### ISSUE THREAD

**Issue by whoabuddy** [aibtcdev/aibtcdev-frontend#91]
We need to think through what this looks like.

Is everything per session? Kick off a convo and resume at any point.

Is everything based on the active session? You can refresh until result comes through?

Do we store the results in the DB for each run, then access that if available in the front end?

**Comment by whoabuddy** [comment]
User only has a single chat. One chat, one chat only.
- will need basic reset / new chat functionality too

User should be able to see a history of everything they've done.

For the backend a session represents an active crew streaming and storing results.

For the frontend it needs to decide difference between resuming session and accessing "complete" conversation.
- pull from DB to fill in chat history
- pull from Websocket to fill in streaming
- when chat complete refresh from DB
- DB only has full complete convo, flush after crew execution (or stop)

Would need to limit context window size based on chat window size. Also could summarize with an LLM call beforehand.

**Comment by human058382928** [comment]
we got persistent chats for the main chat system with ability to reset. I am limited context window as well.
