### ISSUE TITLE
Turn dashboard into full screen chat interface

### ISSUE THREAD

**Issue by whoabuddy** [aibtcdev/aibtcdev-frontend#95]
![image](https://github.com/user-attachments/assets/e4434679-e12e-497c-a826-45d5cd082284)

I think the chat area is a little small to scroll through, and crews down below splits attention.

Should we move crews to a pop-up or pop-out tab, or sidebar type layout?

Should we make the chat full screen and the center of attention?

**Comment by human058382928** [comment]
Done
