### ISSUE TITLE
Display intermediary crew output in expandable container

### ISSUE THREAD

**Issue by whoabuddy** [aibtcdev/aibtcdev-frontend#96]
The main user input goes at the top.

The steps the crew takes should be in an expandable container.
- Title: what it just finished last (title field of returned item)
- Description: contents of step/task/tool that get returned

The final answer goes at the bottom.

That way you can view the steps that were taken in a clear container.

**Comment by biwasbhandari** [comment]
Sorry, I did not get it :(

**Comment by whoabuddy** [comment]
Fixed with all the recent changes :pray:
